# Stage 1: Build
FROM rust:1.94-slim AS builder
WORKDIR /app

# Install dependencies untuk build (misal pkg-config, libssl-dev jika diperlukan sqlx)
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml ./
COPY Cargo.lock ./ 

COPY src ./src
RUN cargo build --release

# Stage 2: Runtime
FROM debian:bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/auth .

EXPOSE 8080
CMD ["./auth"]